/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { Domain, DomainInterface } from "../Domain";
import type { PromiseOrValue } from "../common";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x60c0604052348015600f57600080fd5b504660a0819052601d816025565b608052506096565b60007f47e79534a245952e8b16893a336b85a3d9ea9fa8c573f3d803afb92a794692188230604051602001605a939291906077565b604051602081830303815290604052805190602001209050919050565b92835260208301919091526001600160a01b0316604082015260600190565b60805160a051603f60ac6000395050603f6000f3fe6080604052600080fdfea264697066735822122001cf6b90d42f1cd0b1d377a19570e1a0f063bed6604c294b53efc11c533c7aea64736f6c634300060c0033";

type DomainConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DomainConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Domain__factory extends ContractFactory {
  constructor(...args: DomainConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "Domain";
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Domain> {
    return super.deploy(overrides || {}) as Promise<Domain>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Domain {
    return super.attach(address) as Domain;
  }
  override connect(signer: Signer): Domain__factory {
    return super.connect(signer) as Domain__factory;
  }
  static readonly contractName: "Domain";

  public readonly contractName: "Domain";

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DomainInterface {
    return new utils.Interface(_abi) as DomainInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Domain {
    return new Contract(address, _abi, signerOrProvider) as Domain;
  }
}
