/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DictatorDAO__factory } from "./DictatorDAO__factory";
export { Domain__factory } from "./Domain__factory";
export { IERC20__factory } from "./IERC20__factory";
