/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DOMODAO } from './shared/DOMODAO';
export type { ERC20 } from './shared/ERC20';
export type { FOLD } from './shared/FOLD';
export type { DOMODAO as DictatorDAO } from './shared/DictatorDAO';
export { DOMODAO__factory } from './types/DOMODAO__factory';
export { ERC20__factory } from './types/ERC20__factory';
export { FOLD__factory } from './types/FOLD__factory';
