/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DOMODAO } from './DOMODAO';
export type { ERC20 } from './ERC20';
export type { FOLD } from './FOLD';
<<<<<<< HEAD
export type { DOMODAO as DictatorDAO } from './DictatorDAO';
||||||| c5faaf2


=======

>>>>>>> trunk
export { DOMODAO__factory } from './factories/DOMODAO__factory';
export { ERC20__factory } from './factories/ERC20__factory';
export { FOLD__factory } from './factories/FOLD__factory';
